version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build-fe:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build the FE
  build-rust:
    docker:
      - image: cimg/rust:1.67.1-node
    steps:
      - checkout
      - run: cargo build
workflows:
  build-all:
    jobs:
      - build-fe
      - build-rust
